var jsonData = {
    "content": {
        "__cnt": 9,
        "section": [{
            "__cnt": 7,
            "graphic": "europe.jpg",
            "graphic_asArray": ["europe.jpg"],
            "item": [{
                "__cnt": 17,
                "feedback": "1 Die Gaense means geese.",
                "feedback_asArray": ["1 Die Gaense means geese."],
                "file_audio": "1.mp3",
                "file_audio_asArray": ["1.mp3"],
                "hint": "1 They look like large ducks.",
                "hint_asArray": ["1 They look like large ducks."],
                "lang_en": "one",
                "lang_en_asArray": ["one"],
                "lang_tl": "1 Die Gaense",
                "lang_tl_asArray": ["1 Die Gaense"],
                "left": "180",
                "left_asArray": ["180"],
                "top": "170",
                "top_asArray": ["170"],
                "width": "150",
                "width_asArray": ["150"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "2Die Welt means the world.",
                "feedback_asArray": ["2Die Welt means the world."],
                "file_audio": "2.mp3",
                "file_audio_asArray": ["2.mp3"],
                "hint": "2It's Global.",
                "hint_asArray": ["2It's Global."],
                "lang_en": "2world",
                "lang_en_asArray": ["2world"],
                "lang_tl": "2Die Welt",
                "lang_tl_asArray": ["2Die Welt"],
                "left": "40",
                "left_asArray": ["40"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "100",
                "width_asArray": ["100"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }],
            "item_asArray": [{
                "__cnt": 17,
                "feedback": "1 Die Gaense means geese.",
                "feedback_asArray": ["1 Die Gaense means geese."],
                "file_audio": "1.mp3",
                "file_audio_asArray": ["1.mp3"],
                "hint": "1 They look like large ducks.",
                "hint_asArray": ["1 They look like large ducks."],
                "lang_en": "one",
                "lang_en_asArray": ["one"],
                "lang_tl": "1 Die Gaense",
                "lang_tl_asArray": ["1 Die Gaense"],
                "left": "180",
                "left_asArray": ["180"],
                "top": "170",
                "top_asArray": ["170"],
                "width": "150",
                "width_asArray": ["150"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "2Die Welt means the world.",
                "feedback_asArray": ["2Die Welt means the world."],
                "file_audio": "2.mp3",
                "file_audio_asArray": ["2.mp3"],
                "hint": "2It's Global.",
                "hint_asArray": ["2It's Global."],
                "lang_en": "2world",
                "lang_en_asArray": ["2world"],
                "lang_tl": "2Die Welt",
                "lang_tl_asArray": ["2Die Welt"],
                "left": "40",
                "left_asArray": ["40"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "100",
                "width_asArray": ["100"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }],
            "__text": ["\n\t", "\n    ", "\n    ", "\n  "]
        }, {
            "__cnt": 9,
            "graphic": "iraq.jpg",
            "graphic_asArray": ["iraq.jpg"],
            "item": [{
                "__cnt": 17,
                "feedback": "1 Das Haus mean \"the house.\"",
                "feedback_asArray": ["1 Das Haus mean \"the house.\""],
                "file_audio": "3.mp3",
                "file_audio_asArray": ["3.mp3"],
                "hint": "1 A place to live.",
                "hint_asArray": ["1 A place to live."],
                "lang_en": "1house",
                "lang_en_asArray": ["1house"],
                "lang_tl": "1Das Haus",
                "lang_tl_asArray": ["1Das Haus"],
                "left": "220",
                "left_asArray": ["220"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "220",
                "width_asArray": ["220"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "2Das Essen means \"the food.\"",
                "feedback_asArray": ["2Das Essen means \"the food.\""],
                "file_audio": "4.mp3",
                "file_audio_asArray": ["4.mp3"],
                "hint": "2Eat this at dinner time.",
                "hint_asArray": ["2Eat this at dinner time."],
                "lang_en": "2food",
                "lang_en_asArray": ["2food"],
                "lang_tl": "2Das Essen",
                "lang_tl_asArray": ["2Das Essen"],
                "left": "280",
                "left_asArray": ["280"],
                "top": "120",
                "top_asArray": ["120"],
                "width": "230",
                "width_asArray": ["230"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "3Der Urlaub means \"the vacation.\"",
                "feedback_asArray": ["3Der Urlaub means \"the vacation.\""],
                "file_audio": "5.mp3",
                "file_audio_asArray": ["5.mp3"],
                "hint": "3A journey for pleasure relaxation.",
                "hint_asArray": ["3A journey for pleasure relaxation."],
                "lang_en": "3vacation",
                "lang_en_asArray": ["3vacation"],
                "lang_tl": "3Der Urlaub",
                "lang_tl_asArray": ["3Der Urlaub"],
                "left": "240",
                "left_asArray": ["240"],
                "top": "180",
                "top_asArray": ["180"],
                "width": "250",
                "width_asArray": ["250"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }],
            "item_asArray": [{
                "__cnt": 17,
                "feedback": "1 Das Haus mean \"the house.\"",
                "feedback_asArray": ["1 Das Haus mean \"the house.\""],
                "file_audio": "3.mp3",
                "file_audio_asArray": ["3.mp3"],
                "hint": "1 A place to live.",
                "hint_asArray": ["1 A place to live."],
                "lang_en": "1house",
                "lang_en_asArray": ["1house"],
                "lang_tl": "1Das Haus",
                "lang_tl_asArray": ["1Das Haus"],
                "left": "220",
                "left_asArray": ["220"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "220",
                "width_asArray": ["220"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "2Das Essen means \"the food.\"",
                "feedback_asArray": ["2Das Essen means \"the food.\""],
                "file_audio": "4.mp3",
                "file_audio_asArray": ["4.mp3"],
                "hint": "2Eat this at dinner time.",
                "hint_asArray": ["2Eat this at dinner time."],
                "lang_en": "2food",
                "lang_en_asArray": ["2food"],
                "lang_tl": "2Das Essen",
                "lang_tl_asArray": ["2Das Essen"],
                "left": "280",
                "left_asArray": ["280"],
                "top": "120",
                "top_asArray": ["120"],
                "width": "230",
                "width_asArray": ["230"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "3Der Urlaub means \"the vacation.\"",
                "feedback_asArray": ["3Der Urlaub means \"the vacation.\""],
                "file_audio": "5.mp3",
                "file_audio_asArray": ["5.mp3"],
                "hint": "3A journey for pleasure relaxation.",
                "hint_asArray": ["3A journey for pleasure relaxation."],
                "lang_en": "3vacation",
                "lang_en_asArray": ["3vacation"],
                "lang_tl": "3Der Urlaub",
                "lang_tl_asArray": ["3Der Urlaub"],
                "left": "240",
                "left_asArray": ["240"],
                "top": "180",
                "top_asArray": ["180"],
                "width": "250",
                "width_asArray": ["250"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }],
            "__text": ["\n\t", "\n    ", "\n    ", "\n    ", "\n  "]
        }, {
            "__cnt": 21,
            "graphic": "iraq.jpg",
            "graphic_asArray": ["iraq.jpg"],
            "item": [{
                "__cnt": 17,
                "feedback": "1 Die Gaense means geese.",
                "feedback_asArray": ["1 Die Gaense means geese."],
                "file_audio": "6.mp3",
                "file_audio_asArray": ["6.mp3"],
                "hint": "1 They look like large ducks.",
                "hint_asArray": ["1 They look like large ducks."],
                "lang_en": "one",
                "lang_en_asArray": ["one"],
                "lang_tl": "1 Die Gaense",
                "lang_tl_asArray": ["1 Die Gaense"],
                "left": "180",
                "left_asArray": ["180"],
                "top": "170",
                "top_asArray": ["170"],
                "width": "150",
                "width_asArray": ["150"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "2Die Welt means the world.",
                "feedback_asArray": ["2Die Welt means the world."],
                "file_audio": "7.mp3",
                "file_audio_asArray": ["7.mp3"],
                "hint": "2It's Global.",
                "hint_asArray": ["2It's Global."],
                "lang_en": "2world",
                "lang_en_asArray": ["2world"],
                "lang_tl": "2Die Welt",
                "lang_tl_asArray": ["2Die Welt"],
                "left": "40",
                "left_asArray": ["40"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "100",
                "width_asArray": ["100"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "3Die Guitarre means the guitar.",
                "feedback_asArray": ["3Die Guitarre means the guitar."],
                "file_audio": "8.mp3",
                "file_audio_asArray": ["8.mp3"],
                "hint": "3Jimmy Page of Led Zeppelin plays this instrument.",
                "hint_asArray": ["3Jimmy Page of Led Zeppelin plays this instrument."],
                "lang_en": "3guitar",
                "lang_en_asArray": ["3guitar"],
                "lang_tl": "3Die Guitarre",
                "lang_tl_asArray": ["3Die Guitarre"],
                "left": "0",
                "left_asArray": ["0"],
                "top": "120",
                "top_asArray": ["120"],
                "width": "290",
                "width_asArray": ["290"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "4Der Himmel mean \"the sky.\"",
                "feedback_asArray": ["4Der Himmel mean \"the sky.\""],
                "file_audio": "9.mp3",
                "file_audio_asArray": ["9.mp3"],
                "hint": "4Look up, it's blue.",
                "hint_asArray": ["4Look up, it's blue."],
                "lang_en": "4sky",
                "lang_en_asArray": ["4sky"],
                "lang_tl": "4Der Himmel",
                "lang_tl_asArray": ["4Der Himmel"],
                "left": "40",
                "left_asArray": ["40"],
                "top": "180",
                "top_asArray": ["180"],
                "width": "260",
                "width_asArray": ["260"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "5Der Baum means tree (singular).",
                "feedback_asArray": ["5Der Baum means tree (singular)."],
                "file_audio": "10.mp3",
                "file_audio_asArray": ["10.mp3"],
                "hint": "5They grow in a forest.",
                "hint_asArray": ["5They grow in a forest."],
                "lang_en": "5tree",
                "lang_en_asArray": ["5tree"],
                "lang_tl": "5Der Baum",
                "lang_tl_asArray": ["5Der Baum"],
                "left": "0",
                "left_asArray": ["0"],
                "top": "240",
                "top_asArray": ["240"],
                "width": "210",
                "width_asArray": ["210"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "6Die Sonne means \"the sun.\"",
                "feedback_asArray": ["6Die Sonne means \"the sun.\""],
                "file_audio": "11.mp3",
                "file_audio_asArray": ["11.mp3"],
                "hint": "6This shines on the earth.",
                "hint_asArray": ["6This shines on the earth."],
                "lang_en": "6sun",
                "lang_en_asArray": ["6sun"],
                "lang_tl": "6Die Sonne",
                "lang_tl_asArray": ["6Die Sonne"],
                "left": "250",
                "left_asArray": ["250"],
                "top": "0",
                "top_asArray": ["0"],
                "width": "240",
                "width_asArray": ["240"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "7Das Meer means \"the ocean.\"",
                "feedback_asArray": ["7Das Meer means \"the ocean.\""],
                "file_audio": "12.mp3",
                "file_audio_asArray": ["12.mp3"],
                "hint": "7Fish swim in this.",
                "hint_asArray": ["7Fish swim in this."],
                "lang_en": "7ocean",
                "lang_en_asArray": ["7ocean"],
                "lang_tl": "7Das Meer",
                "lang_tl_asArray": ["7Das Meer"],
                "left": "260",
                "left_asArray": ["260"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "210",
                "width_asArray": ["210"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "8Der Felsen means \"the rock.\"",
                "feedback_asArray": ["8Der Felsen means \"the rock.\""],
                "file_audio": "13.mp3",
                "file_audio_asArray": ["13.mp3"],
                "hint": "8Kid . . .",
                "hint_asArray": ["8Kid . . ."],
                "lang_en": "8rock",
                "lang_en_asArray": ["8rock"],
                "lang_tl": "8Der Felsen",
                "lang_tl_asArray": ["8Der Felsen"],
                "left": "250",
                "left_asArray": ["250"],
                "top": "120",
                "top_asArray": ["120"],
                "width": "250",
                "width_asArray": ["250"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "9Die Blumen means \"the flower.\"",
                "feedback_asArray": ["9Die Blumen means \"the flower.\""],
                "file_audio": "14.mp3",
                "file_audio_asArray": ["14.mp3"],
                "hint": "9They grow in the garden.",
                "hint_asArray": ["9They grow in the garden."],
                "lang_en": "9flower",
                "lang_en_asArray": ["9flower"],
                "lang_tl": "9Die Blumen",
                "lang_tl_asArray": ["9Die Blumen"],
                "left": "260",
                "left_asArray": ["260"],
                "top": "180",
                "top_asArray": ["180"],
                "width": "250",
                "width_asArray": ["250"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }],
            "item_asArray": [{
                "__cnt": 17,
                "feedback": "1 Die Gaense means geese.",
                "feedback_asArray": ["1 Die Gaense means geese."],
                "file_audio": "6.mp3",
                "file_audio_asArray": ["6.mp3"],
                "hint": "1 They look like large ducks.",
                "hint_asArray": ["1 They look like large ducks."],
                "lang_en": "one",
                "lang_en_asArray": ["one"],
                "lang_tl": "1 Die Gaense",
                "lang_tl_asArray": ["1 Die Gaense"],
                "left": "180",
                "left_asArray": ["180"],
                "top": "170",
                "top_asArray": ["170"],
                "width": "150",
                "width_asArray": ["150"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "2Die Welt means the world.",
                "feedback_asArray": ["2Die Welt means the world."],
                "file_audio": "7.mp3",
                "file_audio_asArray": ["7.mp3"],
                "hint": "2It's Global.",
                "hint_asArray": ["2It's Global."],
                "lang_en": "2world",
                "lang_en_asArray": ["2world"],
                "lang_tl": "2Die Welt",
                "lang_tl_asArray": ["2Die Welt"],
                "left": "40",
                "left_asArray": ["40"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "100",
                "width_asArray": ["100"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "3Die Guitarre means the guitar.",
                "feedback_asArray": ["3Die Guitarre means the guitar."],
                "file_audio": "8.mp3",
                "file_audio_asArray": ["8.mp3"],
                "hint": "3Jimmy Page of Led Zeppelin plays this instrument.",
                "hint_asArray": ["3Jimmy Page of Led Zeppelin plays this instrument."],
                "lang_en": "3guitar",
                "lang_en_asArray": ["3guitar"],
                "lang_tl": "3Die Guitarre",
                "lang_tl_asArray": ["3Die Guitarre"],
                "left": "0",
                "left_asArray": ["0"],
                "top": "120",
                "top_asArray": ["120"],
                "width": "290",
                "width_asArray": ["290"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "4Der Himmel mean \"the sky.\"",
                "feedback_asArray": ["4Der Himmel mean \"the sky.\""],
                "file_audio": "9.mp3",
                "file_audio_asArray": ["9.mp3"],
                "hint": "4Look up, it's blue.",
                "hint_asArray": ["4Look up, it's blue."],
                "lang_en": "4sky",
                "lang_en_asArray": ["4sky"],
                "lang_tl": "4Der Himmel",
                "lang_tl_asArray": ["4Der Himmel"],
                "left": "40",
                "left_asArray": ["40"],
                "top": "180",
                "top_asArray": ["180"],
                "width": "260",
                "width_asArray": ["260"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "5Der Baum means tree (singular).",
                "feedback_asArray": ["5Der Baum means tree (singular)."],
                "file_audio": "10.mp3",
                "file_audio_asArray": ["10.mp3"],
                "hint": "5They grow in a forest.",
                "hint_asArray": ["5They grow in a forest."],
                "lang_en": "5tree",
                "lang_en_asArray": ["5tree"],
                "lang_tl": "5Der Baum",
                "lang_tl_asArray": ["5Der Baum"],
                "left": "0",
                "left_asArray": ["0"],
                "top": "240",
                "top_asArray": ["240"],
                "width": "210",
                "width_asArray": ["210"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "6Die Sonne means \"the sun.\"",
                "feedback_asArray": ["6Die Sonne means \"the sun.\""],
                "file_audio": "11.mp3",
                "file_audio_asArray": ["11.mp3"],
                "hint": "6This shines on the earth.",
                "hint_asArray": ["6This shines on the earth."],
                "lang_en": "6sun",
                "lang_en_asArray": ["6sun"],
                "lang_tl": "6Die Sonne",
                "lang_tl_asArray": ["6Die Sonne"],
                "left": "250",
                "left_asArray": ["250"],
                "top": "0",
                "top_asArray": ["0"],
                "width": "240",
                "width_asArray": ["240"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "7Das Meer means \"the ocean.\"",
                "feedback_asArray": ["7Das Meer means \"the ocean.\""],
                "file_audio": "12.mp3",
                "file_audio_asArray": ["12.mp3"],
                "hint": "7Fish swim in this.",
                "hint_asArray": ["7Fish swim in this."],
                "lang_en": "7ocean",
                "lang_en_asArray": ["7ocean"],
                "lang_tl": "7Das Meer",
                "lang_tl_asArray": ["7Das Meer"],
                "left": "260",
                "left_asArray": ["260"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "210",
                "width_asArray": ["210"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "8Der Felsen means \"the rock.\"",
                "feedback_asArray": ["8Der Felsen means \"the rock.\""],
                "file_audio": "13.mp3",
                "file_audio_asArray": ["13.mp3"],
                "hint": "8Kid . . .",
                "hint_asArray": ["8Kid . . ."],
                "lang_en": "8rock",
                "lang_en_asArray": ["8rock"],
                "lang_tl": "8Der Felsen",
                "lang_tl_asArray": ["8Der Felsen"],
                "left": "250",
                "left_asArray": ["250"],
                "top": "120",
                "top_asArray": ["120"],
                "width": "250",
                "width_asArray": ["250"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "9Die Blumen means \"the flower.\"",
                "feedback_asArray": ["9Die Blumen means \"the flower.\""],
                "file_audio": "14.mp3",
                "file_audio_asArray": ["14.mp3"],
                "hint": "9They grow in the garden.",
                "hint_asArray": ["9They grow in the garden."],
                "lang_en": "9flower",
                "lang_en_asArray": ["9flower"],
                "lang_tl": "9Die Blumen",
                "lang_tl_asArray": ["9Die Blumen"],
                "left": "260",
                "left_asArray": ["260"],
                "top": "180",
                "top_asArray": ["180"],
                "width": "250",
                "width_asArray": ["250"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }],
            "__text": ["\n\t", "    \n\t", "\n    ", "\n    ", "\n    ", "\n    ", "\n    ", "\n    ", "\n    ", "\n    ", "\n   "]
        }],
        "section_asArray": [{
            "__cnt": 7,
            "graphic": "europe.jpg",
            "graphic_asArray": ["europe.jpg"],
            "item": [{
                "__cnt": 17,
                "feedback": "1 Die Gaense means geese.",
                "feedback_asArray": ["1 Die Gaense means geese."],
                "file_audio": "1.mp3",
                "file_audio_asArray": ["1.mp3"],
                "hint": "1 They look like large ducks.",
                "hint_asArray": ["1 They look like large ducks."],
                "lang_en": "one",
                "lang_en_asArray": ["one"],
                "lang_tl": "1 Die Gaense",
                "lang_tl_asArray": ["1 Die Gaense"],
                "left": "180",
                "left_asArray": ["180"],
                "top": "170",
                "top_asArray": ["170"],
                "width": "150",
                "width_asArray": ["150"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "2Die Welt means the world.",
                "feedback_asArray": ["2Die Welt means the world."],
                "file_audio": "2.mp3",
                "file_audio_asArray": ["2.mp3"],
                "hint": "2It's Global.",
                "hint_asArray": ["2It's Global."],
                "lang_en": "2world",
                "lang_en_asArray": ["2world"],
                "lang_tl": "2Die Welt",
                "lang_tl_asArray": ["2Die Welt"],
                "left": "40",
                "left_asArray": ["40"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "100",
                "width_asArray": ["100"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }],
            "item_asArray": [{
                "__cnt": 17,
                "feedback": "1 Die Gaense means geese.",
                "feedback_asArray": ["1 Die Gaense means geese."],
                "file_audio": "1.mp3",
                "file_audio_asArray": ["1.mp3"],
                "hint": "1 They look like large ducks.",
                "hint_asArray": ["1 They look like large ducks."],
                "lang_en": "one",
                "lang_en_asArray": ["one"],
                "lang_tl": "1 Die Gaense",
                "lang_tl_asArray": ["1 Die Gaense"],
                "left": "180",
                "left_asArray": ["180"],
                "top": "170",
                "top_asArray": ["170"],
                "width": "150",
                "width_asArray": ["150"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "2Die Welt means the world.",
                "feedback_asArray": ["2Die Welt means the world."],
                "file_audio": "2.mp3",
                "file_audio_asArray": ["2.mp3"],
                "hint": "2It's Global.",
                "hint_asArray": ["2It's Global."],
                "lang_en": "2world",
                "lang_en_asArray": ["2world"],
                "lang_tl": "2Die Welt",
                "lang_tl_asArray": ["2Die Welt"],
                "left": "40",
                "left_asArray": ["40"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "100",
                "width_asArray": ["100"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }],
            "__text": ["\n\t", "\n    ", "\n    ", "\n  "]
        }, {
            "__cnt": 9,
            "graphic": "iraq.jpg",
            "graphic_asArray": ["iraq.jpg"],
            "item": [{
                "__cnt": 17,
                "feedback": "1 Das Haus mean \"the house.\"",
                "feedback_asArray": ["1 Das Haus mean \"the house.\""],
                "file_audio": "3.mp3",
                "file_audio_asArray": ["3.mp3"],
                "hint": "1 A place to live.",
                "hint_asArray": ["1 A place to live."],
                "lang_en": "1house",
                "lang_en_asArray": ["1house"],
                "lang_tl": "1Das Haus",
                "lang_tl_asArray": ["1Das Haus"],
                "left": "220",
                "left_asArray": ["220"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "220",
                "width_asArray": ["220"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "2Das Essen means \"the food.\"",
                "feedback_asArray": ["2Das Essen means \"the food.\""],
                "file_audio": "4.mp3",
                "file_audio_asArray": ["4.mp3"],
                "hint": "2Eat this at dinner time.",
                "hint_asArray": ["2Eat this at dinner time."],
                "lang_en": "2food",
                "lang_en_asArray": ["2food"],
                "lang_tl": "2Das Essen",
                "lang_tl_asArray": ["2Das Essen"],
                "left": "280",
                "left_asArray": ["280"],
                "top": "120",
                "top_asArray": ["120"],
                "width": "230",
                "width_asArray": ["230"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "3Der Urlaub means \"the vacation.\"",
                "feedback_asArray": ["3Der Urlaub means \"the vacation.\""],
                "file_audio": "5.mp3",
                "file_audio_asArray": ["5.mp3"],
                "hint": "3A journey for pleasure relaxation.",
                "hint_asArray": ["3A journey for pleasure relaxation."],
                "lang_en": "3vacation",
                "lang_en_asArray": ["3vacation"],
                "lang_tl": "3Der Urlaub",
                "lang_tl_asArray": ["3Der Urlaub"],
                "left": "240",
                "left_asArray": ["240"],
                "top": "180",
                "top_asArray": ["180"],
                "width": "250",
                "width_asArray": ["250"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }],
            "item_asArray": [{
                "__cnt": 17,
                "feedback": "1 Das Haus mean \"the house.\"",
                "feedback_asArray": ["1 Das Haus mean \"the house.\""],
                "file_audio": "3.mp3",
                "file_audio_asArray": ["3.mp3"],
                "hint": "1 A place to live.",
                "hint_asArray": ["1 A place to live."],
                "lang_en": "1house",
                "lang_en_asArray": ["1house"],
                "lang_tl": "1Das Haus",
                "lang_tl_asArray": ["1Das Haus"],
                "left": "220",
                "left_asArray": ["220"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "220",
                "width_asArray": ["220"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "2Das Essen means \"the food.\"",
                "feedback_asArray": ["2Das Essen means \"the food.\""],
                "file_audio": "4.mp3",
                "file_audio_asArray": ["4.mp3"],
                "hint": "2Eat this at dinner time.",
                "hint_asArray": ["2Eat this at dinner time."],
                "lang_en": "2food",
                "lang_en_asArray": ["2food"],
                "lang_tl": "2Das Essen",
                "lang_tl_asArray": ["2Das Essen"],
                "left": "280",
                "left_asArray": ["280"],
                "top": "120",
                "top_asArray": ["120"],
                "width": "230",
                "width_asArray": ["230"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "3Der Urlaub means \"the vacation.\"",
                "feedback_asArray": ["3Der Urlaub means \"the vacation.\""],
                "file_audio": "5.mp3",
                "file_audio_asArray": ["5.mp3"],
                "hint": "3A journey for pleasure relaxation.",
                "hint_asArray": ["3A journey for pleasure relaxation."],
                "lang_en": "3vacation",
                "lang_en_asArray": ["3vacation"],
                "lang_tl": "3Der Urlaub",
                "lang_tl_asArray": ["3Der Urlaub"],
                "left": "240",
                "left_asArray": ["240"],
                "top": "180",
                "top_asArray": ["180"],
                "width": "250",
                "width_asArray": ["250"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }],
            "__text": ["\n\t", "\n    ", "\n    ", "\n    ", "\n  "]
        }, {
            "__cnt": 21,
            "graphic": "iraq.jpg",
            "graphic_asArray": ["iraq.jpg"],
            "item": [{
                "__cnt": 17,
                "feedback": "1 Die Gaense means geese.",
                "feedback_asArray": ["1 Die Gaense means geese."],
                "file_audio": "6.mp3",
                "file_audio_asArray": ["6.mp3"],
                "hint": "1 They look like large ducks.",
                "hint_asArray": ["1 They look like large ducks."],
                "lang_en": "one",
                "lang_en_asArray": ["one"],
                "lang_tl": "1 Die Gaense",
                "lang_tl_asArray": ["1 Die Gaense"],
                "left": "180",
                "left_asArray": ["180"],
                "top": "170",
                "top_asArray": ["170"],
                "width": "150",
                "width_asArray": ["150"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "2Die Welt means the world.",
                "feedback_asArray": ["2Die Welt means the world."],
                "file_audio": "7.mp3",
                "file_audio_asArray": ["7.mp3"],
                "hint": "2It's Global.",
                "hint_asArray": ["2It's Global."],
                "lang_en": "2world",
                "lang_en_asArray": ["2world"],
                "lang_tl": "2Die Welt",
                "lang_tl_asArray": ["2Die Welt"],
                "left": "40",
                "left_asArray": ["40"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "100",
                "width_asArray": ["100"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "3Die Guitarre means the guitar.",
                "feedback_asArray": ["3Die Guitarre means the guitar."],
                "file_audio": "8.mp3",
                "file_audio_asArray": ["8.mp3"],
                "hint": "3Jimmy Page of Led Zeppelin plays this instrument.",
                "hint_asArray": ["3Jimmy Page of Led Zeppelin plays this instrument."],
                "lang_en": "3guitar",
                "lang_en_asArray": ["3guitar"],
                "lang_tl": "3Die Guitarre",
                "lang_tl_asArray": ["3Die Guitarre"],
                "left": "0",
                "left_asArray": ["0"],
                "top": "120",
                "top_asArray": ["120"],
                "width": "290",
                "width_asArray": ["290"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "4Der Himmel mean \"the sky.\"",
                "feedback_asArray": ["4Der Himmel mean \"the sky.\""],
                "file_audio": "9.mp3",
                "file_audio_asArray": ["9.mp3"],
                "hint": "4Look up, it's blue.",
                "hint_asArray": ["4Look up, it's blue."],
                "lang_en": "4sky",
                "lang_en_asArray": ["4sky"],
                "lang_tl": "4Der Himmel",
                "lang_tl_asArray": ["4Der Himmel"],
                "left": "40",
                "left_asArray": ["40"],
                "top": "180",
                "top_asArray": ["180"],
                "width": "260",
                "width_asArray": ["260"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "5Der Baum means tree (singular).",
                "feedback_asArray": ["5Der Baum means tree (singular)."],
                "file_audio": "10.mp3",
                "file_audio_asArray": ["10.mp3"],
                "hint": "5They grow in a forest.",
                "hint_asArray": ["5They grow in a forest."],
                "lang_en": "5tree",
                "lang_en_asArray": ["5tree"],
                "lang_tl": "5Der Baum",
                "lang_tl_asArray": ["5Der Baum"],
                "left": "0",
                "left_asArray": ["0"],
                "top": "240",
                "top_asArray": ["240"],
                "width": "210",
                "width_asArray": ["210"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "6Die Sonne means \"the sun.\"",
                "feedback_asArray": ["6Die Sonne means \"the sun.\""],
                "file_audio": "11.mp3",
                "file_audio_asArray": ["11.mp3"],
                "hint": "6This shines on the earth.",
                "hint_asArray": ["6This shines on the earth."],
                "lang_en": "6sun",
                "lang_en_asArray": ["6sun"],
                "lang_tl": "6Die Sonne",
                "lang_tl_asArray": ["6Die Sonne"],
                "left": "250",
                "left_asArray": ["250"],
                "top": "0",
                "top_asArray": ["0"],
                "width": "240",
                "width_asArray": ["240"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "7Das Meer means \"the ocean.\"",
                "feedback_asArray": ["7Das Meer means \"the ocean.\""],
                "file_audio": "12.mp3",
                "file_audio_asArray": ["12.mp3"],
                "hint": "7Fish swim in this.",
                "hint_asArray": ["7Fish swim in this."],
                "lang_en": "7ocean",
                "lang_en_asArray": ["7ocean"],
                "lang_tl": "7Das Meer",
                "lang_tl_asArray": ["7Das Meer"],
                "left": "260",
                "left_asArray": ["260"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "210",
                "width_asArray": ["210"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "8Der Felsen means \"the rock.\"",
                "feedback_asArray": ["8Der Felsen means \"the rock.\""],
                "file_audio": "13.mp3",
                "file_audio_asArray": ["13.mp3"],
                "hint": "8Kid . . .",
                "hint_asArray": ["8Kid . . ."],
                "lang_en": "8rock",
                "lang_en_asArray": ["8rock"],
                "lang_tl": "8Der Felsen",
                "lang_tl_asArray": ["8Der Felsen"],
                "left": "250",
                "left_asArray": ["250"],
                "top": "120",
                "top_asArray": ["120"],
                "width": "250",
                "width_asArray": ["250"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "9Die Blumen means \"the flower.\"",
                "feedback_asArray": ["9Die Blumen means \"the flower.\""],
                "file_audio": "14.mp3",
                "file_audio_asArray": ["14.mp3"],
                "hint": "9They grow in the garden.",
                "hint_asArray": ["9They grow in the garden."],
                "lang_en": "9flower",
                "lang_en_asArray": ["9flower"],
                "lang_tl": "9Die Blumen",
                "lang_tl_asArray": ["9Die Blumen"],
                "left": "260",
                "left_asArray": ["260"],
                "top": "180",
                "top_asArray": ["180"],
                "width": "250",
                "width_asArray": ["250"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }],
            "item_asArray": [{
                "__cnt": 17,
                "feedback": "1 Die Gaense means geese.",
                "feedback_asArray": ["1 Die Gaense means geese."],
                "file_audio": "6.mp3",
                "file_audio_asArray": ["6.mp3"],
                "hint": "1 They look like large ducks.",
                "hint_asArray": ["1 They look like large ducks."],
                "lang_en": "one",
                "lang_en_asArray": ["one"],
                "lang_tl": "1 Die Gaense",
                "lang_tl_asArray": ["1 Die Gaense"],
                "left": "180",
                "left_asArray": ["180"],
                "top": "170",
                "top_asArray": ["170"],
                "width": "150",
                "width_asArray": ["150"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "2Die Welt means the world.",
                "feedback_asArray": ["2Die Welt means the world."],
                "file_audio": "7.mp3",
                "file_audio_asArray": ["7.mp3"],
                "hint": "2It's Global.",
                "hint_asArray": ["2It's Global."],
                "lang_en": "2world",
                "lang_en_asArray": ["2world"],
                "lang_tl": "2Die Welt",
                "lang_tl_asArray": ["2Die Welt"],
                "left": "40",
                "left_asArray": ["40"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "100",
                "width_asArray": ["100"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "3Die Guitarre means the guitar.",
                "feedback_asArray": ["3Die Guitarre means the guitar."],
                "file_audio": "8.mp3",
                "file_audio_asArray": ["8.mp3"],
                "hint": "3Jimmy Page of Led Zeppelin plays this instrument.",
                "hint_asArray": ["3Jimmy Page of Led Zeppelin plays this instrument."],
                "lang_en": "3guitar",
                "lang_en_asArray": ["3guitar"],
                "lang_tl": "3Die Guitarre",
                "lang_tl_asArray": ["3Die Guitarre"],
                "left": "0",
                "left_asArray": ["0"],
                "top": "120",
                "top_asArray": ["120"],
                "width": "290",
                "width_asArray": ["290"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "4Der Himmel mean \"the sky.\"",
                "feedback_asArray": ["4Der Himmel mean \"the sky.\""],
                "file_audio": "9.mp3",
                "file_audio_asArray": ["9.mp3"],
                "hint": "4Look up, it's blue.",
                "hint_asArray": ["4Look up, it's blue."],
                "lang_en": "4sky",
                "lang_en_asArray": ["4sky"],
                "lang_tl": "4Der Himmel",
                "lang_tl_asArray": ["4Der Himmel"],
                "left": "40",
                "left_asArray": ["40"],
                "top": "180",
                "top_asArray": ["180"],
                "width": "260",
                "width_asArray": ["260"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "5Der Baum means tree (singular).",
                "feedback_asArray": ["5Der Baum means tree (singular)."],
                "file_audio": "10.mp3",
                "file_audio_asArray": ["10.mp3"],
                "hint": "5They grow in a forest.",
                "hint_asArray": ["5They grow in a forest."],
                "lang_en": "5tree",
                "lang_en_asArray": ["5tree"],
                "lang_tl": "5Der Baum",
                "lang_tl_asArray": ["5Der Baum"],
                "left": "0",
                "left_asArray": ["0"],
                "top": "240",
                "top_asArray": ["240"],
                "width": "210",
                "width_asArray": ["210"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "6Die Sonne means \"the sun.\"",
                "feedback_asArray": ["6Die Sonne means \"the sun.\""],
                "file_audio": "11.mp3",
                "file_audio_asArray": ["11.mp3"],
                "hint": "6This shines on the earth.",
                "hint_asArray": ["6This shines on the earth."],
                "lang_en": "6sun",
                "lang_en_asArray": ["6sun"],
                "lang_tl": "6Die Sonne",
                "lang_tl_asArray": ["6Die Sonne"],
                "left": "250",
                "left_asArray": ["250"],
                "top": "0",
                "top_asArray": ["0"],
                "width": "240",
                "width_asArray": ["240"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "7Das Meer means \"the ocean.\"",
                "feedback_asArray": ["7Das Meer means \"the ocean.\""],
                "file_audio": "12.mp3",
                "file_audio_asArray": ["12.mp3"],
                "hint": "7Fish swim in this.",
                "hint_asArray": ["7Fish swim in this."],
                "lang_en": "7ocean",
                "lang_en_asArray": ["7ocean"],
                "lang_tl": "7Das Meer",
                "lang_tl_asArray": ["7Das Meer"],
                "left": "260",
                "left_asArray": ["260"],
                "top": "60",
                "top_asArray": ["60"],
                "width": "210",
                "width_asArray": ["210"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "8Der Felsen means \"the rock.\"",
                "feedback_asArray": ["8Der Felsen means \"the rock.\""],
                "file_audio": "13.mp3",
                "file_audio_asArray": ["13.mp3"],
                "hint": "8Kid . . .",
                "hint_asArray": ["8Kid . . ."],
                "lang_en": "8rock",
                "lang_en_asArray": ["8rock"],
                "lang_tl": "8Der Felsen",
                "lang_tl_asArray": ["8Der Felsen"],
                "left": "250",
                "left_asArray": ["250"],
                "top": "120",
                "top_asArray": ["120"],
                "width": "250",
                "width_asArray": ["250"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }, {
                "__cnt": 17,
                "feedback": "9Die Blumen means \"the flower.\"",
                "feedback_asArray": ["9Die Blumen means \"the flower.\""],
                "file_audio": "14.mp3",
                "file_audio_asArray": ["14.mp3"],
                "hint": "9They grow in the garden.",
                "hint_asArray": ["9They grow in the garden."],
                "lang_en": "9flower",
                "lang_en_asArray": ["9flower"],
                "lang_tl": "9Die Blumen",
                "lang_tl_asArray": ["9Die Blumen"],
                "left": "260",
                "left_asArray": ["260"],
                "top": "180",
                "top_asArray": ["180"],
                "width": "250",
                "width_asArray": ["250"],
                "__text": ["\n      ", "\n      ", "\n      ", "      \n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "]
            }],
            "__text": ["\n\t", "    \n\t", "\n    ", "\n    ", "\n    ", "\n    ", "\n    ", "\n    ", "\n    ", "\n    ", "\n   "]
        }],
        "_target_language": "French",
        "_xmlns:hs": "http://fieldsupport.dliflc.edu/products/headstart",
        "__text": ["\n  ", "\n  ", "\n  ", "\n\n"]
    }
};