var jsonKeyboard =  {
    "div": {
        "__cnt": 78,
        "button": [{
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "1"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "2"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "3"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "4"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "5"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "6"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "7"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "8"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "9"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "0"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "a"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "b"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "c"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "d"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "e"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "f"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "g"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "h"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "i"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "j"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "k"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "l"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "m"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "n"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "o"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "p"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "q"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "r"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "s"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "t"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "u"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "v"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "w"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "x"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "y"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "z"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "ي"
        }, {
            "__cnt": 2,
            "_onclick": "delClicked()",
            "__text": "Del"
        }],
        "button_asArray": [{
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "1"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "2"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "3"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "4"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "5"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "6"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "7"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "8"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "9"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "0"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "a"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "b"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "c"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "d"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "e"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "f"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "g"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "h"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "i"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "j"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "k"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "l"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "m"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "n"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "o"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "p"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "q"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "r"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "s"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "t"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "u"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "v"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "w"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "x"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "y"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "z"
        }, {
            "__cnt": 2,
            "_onclick": "letterClicked(this)",
            "__text": "ي"
        }, {
            "__cnt": 2,
            "_onclick": "delClicked()",
            "__text": "Del"
        }],
        "_id": "keyboard",
        "__text": []
    }
};