var jsonData = {
    "content": {
        "__cnt": 40,
        "digit": [{
            "__cnt": 3,
            "_english": "0",
            "_audio": "0.mp3",
            "__text": "٠"
        }, {
            "__cnt": 3,
            "_english": "1",
            "_audio": "1.mp3",
            "__text": "١"
        }, {
            "__cnt": 3,
            "_english": "2",
            "_audio": "2.mp3",
            "__text": "٢"
        }, {
            "__cnt": 3,
            "_english": "3",
            "_audio": "3.mp3",
            "__text": "٣"
        }, {
            "__cnt": 3,
            "_english": "4",
            "_audio": "4.mp3",
            "__text": "٤"
        }, {
            "__cnt": 3,
            "_english": "5",
            "_audio": "5.mp3",
            "__text": "٥"
        }, {
            "__cnt": 3,
            "_english": "6",
            "_audio": "6.mp3",
            "__text": "٥"
        }, {
            "__cnt": 3,
            "_english": "7",
            "_audio": "7.mp3",
            "__text": "٧"
        }, {
            "__cnt": 3,
            "_english": "8",
            "_audio": "8.mp3",
            "__text": "٨"
        }, {
            "__cnt": 3,
            "_english": "9",
            "_audio": "9.mp3",
            "__text": "٩"
        }],
        "digit_asArray": [{
            "__cnt": 3,
            "_english": "0",
            "_audio": "0.mp3",
            "__text": "٠"
        }, {
            "__cnt": 3,
            "_english": "1",
            "_audio": "1.mp3",
            "__text": "١"
        }, {
            "__cnt": 3,
            "_english": "2",
            "_audio": "2.mp3",
            "__text": "٢"
        }, {
            "__cnt": 3,
            "_english": "3",
            "_audio": "3.mp3",
            "__text": "٣"
        }, {
            "__cnt": 3,
            "_english": "4",
            "_audio": "4.mp3",
            "__text": "٤"
        }, {
            "__cnt": 3,
            "_english": "5",
            "_audio": "5.mp3",
            "__text": "٥"
        }, {
            "__cnt": 3,
            "_english": "6",
            "_audio": "6.mp3",
            "__text": "٥"
        }, {
            "__cnt": 3,
            "_english": "7",
            "_audio": "7.mp3",
            "__text": "٧"
        }, {
            "__cnt": 3,
            "_english": "8",
            "_audio": "8.mp3",
            "__text": "٨"
        }, {
            "__cnt": 3,
            "_english": "9",
            "_audio": "9.mp3",
            "__text": "٩"
        }],
        "item": [{
            "__cnt": 2,
            "_english": "1200234",
            "_audio": "ir_phone_2039989.mp3"
        }, {
            "__cnt": 2,
            "_english": "2039989",
            "_audio": "ir_phone_2039989.mp3"
        }, {
            "__cnt": 2,
            "_english": "3212320",
            "_audio": "ir_phone_3212320.mp3"
        }, {
            "__cnt": 2,
            "_english": "4016678",
            "_audio": "ir_phone_4016678.mp3"
        }, {
            "__cnt": 2,
            "_english": "5530584",
            "_audio": "ir_phone_5530584.mp3"
        }, {
            "__cnt": 2,
            "_english": "5554939",
            "_audio": "ir_phone_5554939.mp3"
        }, {
            "__cnt": 2,
            "_english": "6236423",
            "_audio": "ir_phone_6236423.mp3"
        }, {
            "__cnt": 2,
            "_english": "7781624",
            "_audio": "ir_phone_7781624.mp3"
        }, {
            "__cnt": 2,
            "_english": "9980912",
            "_audio": "ir_phone_9980912.mp3"
        }],
        "item_asArray": [{
            "__cnt": 2,
            "_english": "1200234",
            "_audio": "ir_phone_2039989.mp3"
        }, {
            "__cnt": 2,
            "_english": "2039989",
            "_audio": "ir_phone_2039989.mp3"
        }, {
            "__cnt": 2,
            "_english": "3212320",
            "_audio": "ir_phone_3212320.mp3"
        }, {
            "__cnt": 2,
            "_english": "4016678",
            "_audio": "ir_phone_4016678.mp3"
        }, {
            "__cnt": 2,
            "_english": "5530584",
            "_audio": "ir_phone_5530584.mp3"
        }, {
            "__cnt": 2,
            "_english": "5554939",
            "_audio": "ir_phone_5554939.mp3"
        }, {
            "__cnt": 2,
            "_english": "6236423",
            "_audio": "ir_phone_6236423.mp3"
        }, {
            "__cnt": 2,
            "_english": "7781624",
            "_audio": "ir_phone_7781624.mp3"
        }, {
            "__cnt": 2,
            "_english": "9980912",
            "_audio": "ir_phone_9980912.mp3"
        }],
        "_xmlns:hs": "http://fieldsupport.lingnet.org/products/headstart",
        "__text": ["\n\t", "\n\t", "\n\t", "\n\t", "\n\t", "\n\t", "\n\t", "\n\t", "\n\t", "\n\t", "\n\n\t", "\n\t", "\n\t", "\n\t", "\n\t", "\n\t", "\n\t", "\n\t", "\n\t", "\n"]
    }
};